#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="D:\\PTUD\\NHOM01_DETAI04_PTUD_13A_2019\\DB\\QLLD.MDF")]
	public partial class dbQuanLyDuAnDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBangChamCong(BangChamCong instance);
    partial void UpdateBangChamCong(BangChamCong instance);
    partial void DeleteBangChamCong(BangChamCong instance);
    partial void InsertBangLuong(BangLuong instance);
    partial void UpdateBangLuong(BangLuong instance);
    partial void DeleteBangLuong(BangLuong instance);
    partial void InsertChucVu(ChucVu instance);
    partial void UpdateChucVu(ChucVu instance);
    partial void DeleteChucVu(ChucVu instance);
    partial void InsertCongViecDuAn(CongViecDuAn instance);
    partial void UpdateCongViecDuAn(CongViecDuAn instance);
    partial void DeleteCongViecDuAn(CongViecDuAn instance);
    partial void InsertDiaChi(DiaChi instance);
    partial void UpdateDiaChi(DiaChi instance);
    partial void DeleteDiaChi(DiaChi instance);
    partial void InsertDuAn(DuAn instance);
    partial void UpdateDuAn(DuAn instance);
    partial void DeleteDuAn(DuAn instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertPhongBan(PhongBan instance);
    partial void UpdatePhongBan(PhongBan instance);
    partial void DeletePhongBan(PhongBan instance);
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    partial void InsertThaoLuanDuAn(ThaoLuanDuAn instance);
    partial void UpdateThaoLuanDuAn(ThaoLuanDuAn instance);
    partial void DeleteThaoLuanDuAn(ThaoLuanDuAn instance);
    #endregion
		
		public dbQuanLyDuAnDataContext() : 
				base(global::DAL.Properties.Settings.Default.D__PTUD_NHOM01_DETAI04_PTUD_13A_2019_DB_QLLD_MDFConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbQuanLyDuAnDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQuanLyDuAnDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQuanLyDuAnDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQuanLyDuAnDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BangChamCong> BangChamCongs
		{
			get
			{
				return this.GetTable<BangChamCong>();
			}
		}
		
		public System.Data.Linq.Table<BangLuong> BangLuongs
		{
			get
			{
				return this.GetTable<BangLuong>();
			}
		}
		
		public System.Data.Linq.Table<ChucVu> ChucVus
		{
			get
			{
				return this.GetTable<ChucVu>();
			}
		}
		
		public System.Data.Linq.Table<CongViecDuAn> CongViecDuAns
		{
			get
			{
				return this.GetTable<CongViecDuAn>();
			}
		}
		
		public System.Data.Linq.Table<DiaChi> DiaChis
		{
			get
			{
				return this.GetTable<DiaChi>();
			}
		}
		
		public System.Data.Linq.Table<DuAn> DuAns
		{
			get
			{
				return this.GetTable<DuAn>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<PhongBan> PhongBans
		{
			get
			{
				return this.GetTable<PhongBan>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<ThaoLuanDuAn> ThaoLuanDuAns
		{
			get
			{
				return this.GetTable<ThaoLuanDuAn>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BangChamCong")]
	public partial class BangChamCong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maNhanVien;
		
		private string _maDuAn;
		
		private int _soNgayCong;
		
		private System.Nullable<System.DateTime> _thangChamCong;
		
		private EntityRef<DuAn> _DuAn;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNhanVienChanging(string value);
    partial void OnmaNhanVienChanged();
    partial void OnmaDuAnChanging(string value);
    partial void OnmaDuAnChanged();
    partial void OnsoNgayCongChanging(int value);
    partial void OnsoNgayCongChanged();
    partial void OnthangChamCongChanging(System.Nullable<System.DateTime> value);
    partial void OnthangChamCongChanged();
    #endregion
		
		public BangChamCong()
		{
			this._DuAn = default(EntityRef<DuAn>);
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVien", DbType="NChar(14) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maNhanVien
		{
			get
			{
				return this._maNhanVien;
			}
			set
			{
				if ((this._maNhanVien != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._maNhanVien = value;
					this.SendPropertyChanged("maNhanVien");
					this.OnmaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maDuAn", DbType="NChar(14) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maDuAn
		{
			get
			{
				return this._maDuAn;
			}
			set
			{
				if ((this._maDuAn != value))
				{
					if (this._DuAn.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaDuAnChanging(value);
					this.SendPropertyChanging();
					this._maDuAn = value;
					this.SendPropertyChanged("maDuAn");
					this.OnmaDuAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soNgayCong", DbType="Int NOT NULL")]
		public int soNgayCong
		{
			get
			{
				return this._soNgayCong;
			}
			set
			{
				if ((this._soNgayCong != value))
				{
					this.OnsoNgayCongChanging(value);
					this.SendPropertyChanging();
					this._soNgayCong = value;
					this.SendPropertyChanged("soNgayCong");
					this.OnsoNgayCongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thangChamCong", DbType="DateTime")]
		public System.Nullable<System.DateTime> thangChamCong
		{
			get
			{
				return this._thangChamCong;
			}
			set
			{
				if ((this._thangChamCong != value))
				{
					this.OnthangChamCongChanging(value);
					this.SendPropertyChanging();
					this._thangChamCong = value;
					this.SendPropertyChanged("thangChamCong");
					this.OnthangChamCongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DuAn_BangChamCong", Storage="_DuAn", ThisKey="maDuAn", OtherKey="maDuAn", IsForeignKey=true)]
		public DuAn DuAn
		{
			get
			{
				return this._DuAn.Entity;
			}
			set
			{
				DuAn previousValue = this._DuAn.Entity;
				if (((previousValue != value) 
							|| (this._DuAn.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DuAn.Entity = null;
						previousValue.BangChamCongs.Remove(this);
					}
					this._DuAn.Entity = value;
					if ((value != null))
					{
						value.BangChamCongs.Add(this);
						this._maDuAn = value.maDuAn;
					}
					else
					{
						this._maDuAn = default(string);
					}
					this.SendPropertyChanged("DuAn");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_BangChamCong", Storage="_NhanVien", ThisKey="maNhanVien", OtherKey="maNhanVien", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.BangChamCongs.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.BangChamCongs.Add(this);
						this._maNhanVien = value.maNhanVien;
					}
					else
					{
						this._maNhanVien = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BangLuong")]
	public partial class BangLuong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maBangLuong;
		
		private System.DateTime _ngayPhatLuong;
		
		private double _tongTienLuong;
		
		private string _maNhanVien;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaBangLuongChanging(string value);
    partial void OnmaBangLuongChanged();
    partial void OnngayPhatLuongChanging(System.DateTime value);
    partial void OnngayPhatLuongChanged();
    partial void OntongTienLuongChanging(double value);
    partial void OntongTienLuongChanged();
    partial void OnmaNhanVienChanging(string value);
    partial void OnmaNhanVienChanged();
    #endregion
		
		public BangLuong()
		{
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maBangLuong", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maBangLuong
		{
			get
			{
				return this._maBangLuong;
			}
			set
			{
				if ((this._maBangLuong != value))
				{
					this.OnmaBangLuongChanging(value);
					this.SendPropertyChanging();
					this._maBangLuong = value;
					this.SendPropertyChanged("maBangLuong");
					this.OnmaBangLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayPhatLuong", DbType="Date NOT NULL")]
		public System.DateTime ngayPhatLuong
		{
			get
			{
				return this._ngayPhatLuong;
			}
			set
			{
				if ((this._ngayPhatLuong != value))
				{
					this.OnngayPhatLuongChanging(value);
					this.SendPropertyChanging();
					this._ngayPhatLuong = value;
					this.SendPropertyChanged("ngayPhatLuong");
					this.OnngayPhatLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongTienLuong", DbType="Float NOT NULL")]
		public double tongTienLuong
		{
			get
			{
				return this._tongTienLuong;
			}
			set
			{
				if ((this._tongTienLuong != value))
				{
					this.OntongTienLuongChanging(value);
					this.SendPropertyChanging();
					this._tongTienLuong = value;
					this.SendPropertyChanged("tongTienLuong");
					this.OntongTienLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVien", DbType="NChar(14) NOT NULL", CanBeNull=false)]
		public string maNhanVien
		{
			get
			{
				return this._maNhanVien;
			}
			set
			{
				if ((this._maNhanVien != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._maNhanVien = value;
					this.SendPropertyChanged("maNhanVien");
					this.OnmaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_BangLuong", Storage="_NhanVien", ThisKey="maNhanVien", OtherKey="maNhanVien", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.BangLuongs.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.BangLuongs.Add(this);
						this._maNhanVien = value.maNhanVien;
					}
					else
					{
						this._maNhanVien = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChucVu")]
	public partial class ChucVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maChucVu;
		
		private string _tenChucVu;
		
		private double _heSoLuong;
		
		private EntitySet<NhanVien> _NhanViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaChucVuChanging(string value);
    partial void OnmaChucVuChanged();
    partial void OntenChucVuChanging(string value);
    partial void OntenChucVuChanged();
    partial void OnheSoLuongChanging(double value);
    partial void OnheSoLuongChanged();
    #endregion
		
		public ChucVu()
		{
			this._NhanViens = new EntitySet<NhanVien>(new Action<NhanVien>(this.attach_NhanViens), new Action<NhanVien>(this.detach_NhanViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maChucVu", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maChucVu
		{
			get
			{
				return this._maChucVu;
			}
			set
			{
				if ((this._maChucVu != value))
				{
					this.OnmaChucVuChanging(value);
					this.SendPropertyChanging();
					this._maChucVu = value;
					this.SendPropertyChanged("maChucVu");
					this.OnmaChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenChucVu", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenChucVu
		{
			get
			{
				return this._tenChucVu;
			}
			set
			{
				if ((this._tenChucVu != value))
				{
					this.OntenChucVuChanging(value);
					this.SendPropertyChanging();
					this._tenChucVu = value;
					this.SendPropertyChanged("tenChucVu");
					this.OntenChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_heSoLuong", DbType="Float NOT NULL")]
		public double heSoLuong
		{
			get
			{
				return this._heSoLuong;
			}
			set
			{
				if ((this._heSoLuong != value))
				{
					this.OnheSoLuongChanging(value);
					this.SendPropertyChanging();
					this._heSoLuong = value;
					this.SendPropertyChanged("heSoLuong");
					this.OnheSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChucVu_NhanVien", Storage="_NhanViens", ThisKey="maChucVu", OtherKey="maChucVu")]
		public EntitySet<NhanVien> NhanViens
		{
			get
			{
				return this._NhanViens;
			}
			set
			{
				this._NhanViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.ChucVu = this;
		}
		
		private void detach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.ChucVu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CongViecDuAn")]
	public partial class CongViecDuAn : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maCongViec;
		
		private string _tenCongViec;
		
		private System.Nullable<System.DateTime> _ngayBatDau;
		
		private System.Nullable<System.DateTime> _ngayKetThuc;
		
		private string _doUuTien;
		
		private string _maDuAn;
		
		private EntityRef<DuAn> _DuAn;
		
		private EntityRef<DuAn> _DuAn1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaCongViecChanging(int value);
    partial void OnmaCongViecChanged();
    partial void OntenCongViecChanging(string value);
    partial void OntenCongViecChanged();
    partial void OnngayBatDauChanging(System.Nullable<System.DateTime> value);
    partial void OnngayBatDauChanged();
    partial void OnngayKetThucChanging(System.Nullable<System.DateTime> value);
    partial void OnngayKetThucChanged();
    partial void OndoUuTienChanging(string value);
    partial void OndoUuTienChanged();
    partial void OnmaDuAnChanging(string value);
    partial void OnmaDuAnChanged();
    #endregion
		
		public CongViecDuAn()
		{
			this._DuAn = default(EntityRef<DuAn>);
			this._DuAn1 = default(EntityRef<DuAn>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCongViec", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maCongViec
		{
			get
			{
				return this._maCongViec;
			}
			set
			{
				if ((this._maCongViec != value))
				{
					this.OnmaCongViecChanging(value);
					this.SendPropertyChanging();
					this._maCongViec = value;
					this.SendPropertyChanged("maCongViec");
					this.OnmaCongViecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenCongViec", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string tenCongViec
		{
			get
			{
				return this._tenCongViec;
			}
			set
			{
				if ((this._tenCongViec != value))
				{
					this.OntenCongViecChanging(value);
					this.SendPropertyChanging();
					this._tenCongViec = value;
					this.SendPropertyChanged("tenCongViec");
					this.OntenCongViecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayBatDau", DbType="Date")]
		public System.Nullable<System.DateTime> ngayBatDau
		{
			get
			{
				return this._ngayBatDau;
			}
			set
			{
				if ((this._ngayBatDau != value))
				{
					this.OnngayBatDauChanging(value);
					this.SendPropertyChanging();
					this._ngayBatDau = value;
					this.SendPropertyChanged("ngayBatDau");
					this.OnngayBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayKetThuc", DbType="Date")]
		public System.Nullable<System.DateTime> ngayKetThuc
		{
			get
			{
				return this._ngayKetThuc;
			}
			set
			{
				if ((this._ngayKetThuc != value))
				{
					this.OnngayKetThucChanging(value);
					this.SendPropertyChanging();
					this._ngayKetThuc = value;
					this.SendPropertyChanged("ngayKetThuc");
					this.OnngayKetThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doUuTien", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string doUuTien
		{
			get
			{
				return this._doUuTien;
			}
			set
			{
				if ((this._doUuTien != value))
				{
					this.OndoUuTienChanging(value);
					this.SendPropertyChanging();
					this._doUuTien = value;
					this.SendPropertyChanged("doUuTien");
					this.OndoUuTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maDuAn", DbType="NChar(14)")]
		public string maDuAn
		{
			get
			{
				return this._maDuAn;
			}
			set
			{
				if ((this._maDuAn != value))
				{
					if ((this._DuAn.HasLoadedOrAssignedValue || this._DuAn1.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaDuAnChanging(value);
					this.SendPropertyChanging();
					this._maDuAn = value;
					this.SendPropertyChanged("maDuAn");
					this.OnmaDuAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DuAn_CongViecDuAn", Storage="_DuAn", ThisKey="maDuAn", OtherKey="maDuAn", IsForeignKey=true, DeleteRule="CASCADE")]
		public DuAn DuAn
		{
			get
			{
				return this._DuAn.Entity;
			}
			set
			{
				DuAn previousValue = this._DuAn.Entity;
				if (((previousValue != value) 
							|| (this._DuAn.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DuAn.Entity = null;
						previousValue.CongViecDuAns.Remove(this);
					}
					this._DuAn.Entity = value;
					if ((value != null))
					{
						value.CongViecDuAns.Add(this);
						this._maDuAn = value.maDuAn;
					}
					else
					{
						this._maDuAn = default(string);
					}
					this.SendPropertyChanged("DuAn");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DuAn_CongViecDuAn1", Storage="_DuAn1", ThisKey="maDuAn", OtherKey="maDuAn", IsForeignKey=true)]
		public DuAn DuAn1
		{
			get
			{
				return this._DuAn1.Entity;
			}
			set
			{
				DuAn previousValue = this._DuAn1.Entity;
				if (((previousValue != value) 
							|| (this._DuAn1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DuAn1.Entity = null;
						previousValue.CongViecDuAns1.Remove(this);
					}
					this._DuAn1.Entity = value;
					if ((value != null))
					{
						value.CongViecDuAns1.Add(this);
						this._maDuAn = value.maDuAn;
					}
					else
					{
						this._maDuAn = default(string);
					}
					this.SendPropertyChanged("DuAn1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DiaChi")]
	public partial class DiaChi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maDiaChi;
		
		private string _diaChiThanhPho;
		
		private string _diaChiQuan;
		
		private string _diaChiPhuong;
		
		private string _diaChiNha;
		
		private EntitySet<DuAn> _DuAns;
		
		private EntitySet<DuAn> _DuAns1;
		
		private EntitySet<NhanVien> _NhanViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaDiaChiChanging(string value);
    partial void OnmaDiaChiChanged();
    partial void OndiaChiThanhPhoChanging(string value);
    partial void OndiaChiThanhPhoChanged();
    partial void OndiaChiQuanChanging(string value);
    partial void OndiaChiQuanChanged();
    partial void OndiaChiPhuongChanging(string value);
    partial void OndiaChiPhuongChanged();
    partial void OndiaChiNhaChanging(string value);
    partial void OndiaChiNhaChanged();
    #endregion
		
		public DiaChi()
		{
			this._DuAns = new EntitySet<DuAn>(new Action<DuAn>(this.attach_DuAns), new Action<DuAn>(this.detach_DuAns));
			this._DuAns1 = new EntitySet<DuAn>(new Action<DuAn>(this.attach_DuAns1), new Action<DuAn>(this.detach_DuAns1));
			this._NhanViens = new EntitySet<NhanVien>(new Action<NhanVien>(this.attach_NhanViens), new Action<NhanVien>(this.detach_NhanViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maDiaChi", DbType="NChar(14) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maDiaChi
		{
			get
			{
				return this._maDiaChi;
			}
			set
			{
				if ((this._maDiaChi != value))
				{
					this.OnmaDiaChiChanging(value);
					this.SendPropertyChanging();
					this._maDiaChi = value;
					this.SendPropertyChanged("maDiaChi");
					this.OnmaDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChiThanhPho", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string diaChiThanhPho
		{
			get
			{
				return this._diaChiThanhPho;
			}
			set
			{
				if ((this._diaChiThanhPho != value))
				{
					this.OndiaChiThanhPhoChanging(value);
					this.SendPropertyChanging();
					this._diaChiThanhPho = value;
					this.SendPropertyChanged("diaChiThanhPho");
					this.OndiaChiThanhPhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChiQuan", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string diaChiQuan
		{
			get
			{
				return this._diaChiQuan;
			}
			set
			{
				if ((this._diaChiQuan != value))
				{
					this.OndiaChiQuanChanging(value);
					this.SendPropertyChanging();
					this._diaChiQuan = value;
					this.SendPropertyChanged("diaChiQuan");
					this.OndiaChiQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChiPhuong", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string diaChiPhuong
		{
			get
			{
				return this._diaChiPhuong;
			}
			set
			{
				if ((this._diaChiPhuong != value))
				{
					this.OndiaChiPhuongChanging(value);
					this.SendPropertyChanging();
					this._diaChiPhuong = value;
					this.SendPropertyChanged("diaChiPhuong");
					this.OndiaChiPhuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChiNha", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string diaChiNha
		{
			get
			{
				return this._diaChiNha;
			}
			set
			{
				if ((this._diaChiNha != value))
				{
					this.OndiaChiNhaChanging(value);
					this.SendPropertyChanging();
					this._diaChiNha = value;
					this.SendPropertyChanged("diaChiNha");
					this.OndiaChiNhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiaChi_DuAn", Storage="_DuAns", ThisKey="maDiaChi", OtherKey="maDiaChi")]
		public EntitySet<DuAn> DuAns
		{
			get
			{
				return this._DuAns;
			}
			set
			{
				this._DuAns.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiaChi_DuAn1", Storage="_DuAns1", ThisKey="maDiaChi", OtherKey="maDiaChi")]
		public EntitySet<DuAn> DuAns1
		{
			get
			{
				return this._DuAns1;
			}
			set
			{
				this._DuAns1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiaChi_NhanVien", Storage="_NhanViens", ThisKey="maDiaChi", OtherKey="maDiaChi")]
		public EntitySet<NhanVien> NhanViens
		{
			get
			{
				return this._NhanViens;
			}
			set
			{
				this._NhanViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DuAns(DuAn entity)
		{
			this.SendPropertyChanging();
			entity.DiaChi = this;
		}
		
		private void detach_DuAns(DuAn entity)
		{
			this.SendPropertyChanging();
			entity.DiaChi = null;
		}
		
		private void attach_DuAns1(DuAn entity)
		{
			this.SendPropertyChanging();
			entity.DiaChi1 = this;
		}
		
		private void detach_DuAns1(DuAn entity)
		{
			this.SendPropertyChanging();
			entity.DiaChi1 = null;
		}
		
		private void attach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.DiaChi = this;
		}
		
		private void detach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.DiaChi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DuAn")]
	public partial class DuAn : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maDuAn;
		
		private string _tenDuAn;
		
		private string _maDiaChi;
		
		private System.DateTime _ngayKhoiCong;
		
		private System.DateTime _ngayHoanThanh;
		
		private string _trangThai;
		
		private string _chuDauTu;
		
		private System.Nullable<System.DateTime> _ngayHoanThanhDuKien;
		
		private System.Nullable<decimal> _kinhPhiDauTu;
		
		private string _loaiCongTrinh;
		
		private EntitySet<BangChamCong> _BangChamCongs;
		
		private EntitySet<CongViecDuAn> _CongViecDuAns;
		
		private EntitySet<CongViecDuAn> _CongViecDuAns1;
		
		private EntitySet<ThaoLuanDuAn> _ThaoLuanDuAns;
		
		private EntitySet<ThaoLuanDuAn> _ThaoLuanDuAns1;
		
		private EntityRef<DiaChi> _DiaChi;
		
		private EntityRef<DiaChi> _DiaChi1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaDuAnChanging(string value);
    partial void OnmaDuAnChanged();
    partial void OntenDuAnChanging(string value);
    partial void OntenDuAnChanged();
    partial void OnmaDiaChiChanging(string value);
    partial void OnmaDiaChiChanged();
    partial void OnngayKhoiCongChanging(System.DateTime value);
    partial void OnngayKhoiCongChanged();
    partial void OnngayHoanThanhChanging(System.DateTime value);
    partial void OnngayHoanThanhChanged();
    partial void OntrangThaiChanging(string value);
    partial void OntrangThaiChanged();
    partial void OnchuDauTuChanging(string value);
    partial void OnchuDauTuChanged();
    partial void OnngayHoanThanhDuKienChanging(System.Nullable<System.DateTime> value);
    partial void OnngayHoanThanhDuKienChanged();
    partial void OnkinhPhiDauTuChanging(System.Nullable<decimal> value);
    partial void OnkinhPhiDauTuChanged();
    partial void OnloaiCongTrinhChanging(string value);
    partial void OnloaiCongTrinhChanged();
    #endregion
		
		public DuAn()
		{
			this._BangChamCongs = new EntitySet<BangChamCong>(new Action<BangChamCong>(this.attach_BangChamCongs), new Action<BangChamCong>(this.detach_BangChamCongs));
			this._CongViecDuAns = new EntitySet<CongViecDuAn>(new Action<CongViecDuAn>(this.attach_CongViecDuAns), new Action<CongViecDuAn>(this.detach_CongViecDuAns));
			this._CongViecDuAns1 = new EntitySet<CongViecDuAn>(new Action<CongViecDuAn>(this.attach_CongViecDuAns1), new Action<CongViecDuAn>(this.detach_CongViecDuAns1));
			this._ThaoLuanDuAns = new EntitySet<ThaoLuanDuAn>(new Action<ThaoLuanDuAn>(this.attach_ThaoLuanDuAns), new Action<ThaoLuanDuAn>(this.detach_ThaoLuanDuAns));
			this._ThaoLuanDuAns1 = new EntitySet<ThaoLuanDuAn>(new Action<ThaoLuanDuAn>(this.attach_ThaoLuanDuAns1), new Action<ThaoLuanDuAn>(this.detach_ThaoLuanDuAns1));
			this._DiaChi = default(EntityRef<DiaChi>);
			this._DiaChi1 = default(EntityRef<DiaChi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maDuAn", DbType="NChar(14) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maDuAn
		{
			get
			{
				return this._maDuAn;
			}
			set
			{
				if ((this._maDuAn != value))
				{
					this.OnmaDuAnChanging(value);
					this.SendPropertyChanging();
					this._maDuAn = value;
					this.SendPropertyChanged("maDuAn");
					this.OnmaDuAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenDuAn", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenDuAn
		{
			get
			{
				return this._tenDuAn;
			}
			set
			{
				if ((this._tenDuAn != value))
				{
					this.OntenDuAnChanging(value);
					this.SendPropertyChanging();
					this._tenDuAn = value;
					this.SendPropertyChanged("tenDuAn");
					this.OntenDuAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maDiaChi", DbType="NChar(14) NOT NULL", CanBeNull=false)]
		public string maDiaChi
		{
			get
			{
				return this._maDiaChi;
			}
			set
			{
				if ((this._maDiaChi != value))
				{
					if ((this._DiaChi.HasLoadedOrAssignedValue || this._DiaChi1.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaDiaChiChanging(value);
					this.SendPropertyChanging();
					this._maDiaChi = value;
					this.SendPropertyChanged("maDiaChi");
					this.OnmaDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayKhoiCong", DbType="Date NOT NULL")]
		public System.DateTime ngayKhoiCong
		{
			get
			{
				return this._ngayKhoiCong;
			}
			set
			{
				if ((this._ngayKhoiCong != value))
				{
					this.OnngayKhoiCongChanging(value);
					this.SendPropertyChanging();
					this._ngayKhoiCong = value;
					this.SendPropertyChanged("ngayKhoiCong");
					this.OnngayKhoiCongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayHoanThanh", DbType="Date NOT NULL")]
		public System.DateTime ngayHoanThanh
		{
			get
			{
				return this._ngayHoanThanh;
			}
			set
			{
				if ((this._ngayHoanThanh != value))
				{
					this.OnngayHoanThanhChanging(value);
					this.SendPropertyChanging();
					this._ngayHoanThanh = value;
					this.SendPropertyChanged("ngayHoanThanh");
					this.OnngayHoanThanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chuDauTu", DbType="NVarChar(50)")]
		public string chuDauTu
		{
			get
			{
				return this._chuDauTu;
			}
			set
			{
				if ((this._chuDauTu != value))
				{
					this.OnchuDauTuChanging(value);
					this.SendPropertyChanging();
					this._chuDauTu = value;
					this.SendPropertyChanged("chuDauTu");
					this.OnchuDauTuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayHoanThanhDuKien", DbType="Date")]
		public System.Nullable<System.DateTime> ngayHoanThanhDuKien
		{
			get
			{
				return this._ngayHoanThanhDuKien;
			}
			set
			{
				if ((this._ngayHoanThanhDuKien != value))
				{
					this.OnngayHoanThanhDuKienChanging(value);
					this.SendPropertyChanging();
					this._ngayHoanThanhDuKien = value;
					this.SendPropertyChanged("ngayHoanThanhDuKien");
					this.OnngayHoanThanhDuKienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kinhPhiDauTu", DbType="Money")]
		public System.Nullable<decimal> kinhPhiDauTu
		{
			get
			{
				return this._kinhPhiDauTu;
			}
			set
			{
				if ((this._kinhPhiDauTu != value))
				{
					this.OnkinhPhiDauTuChanging(value);
					this.SendPropertyChanging();
					this._kinhPhiDauTu = value;
					this.SendPropertyChanged("kinhPhiDauTu");
					this.OnkinhPhiDauTuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaiCongTrinh", DbType="NVarChar(50)")]
		public string loaiCongTrinh
		{
			get
			{
				return this._loaiCongTrinh;
			}
			set
			{
				if ((this._loaiCongTrinh != value))
				{
					this.OnloaiCongTrinhChanging(value);
					this.SendPropertyChanging();
					this._loaiCongTrinh = value;
					this.SendPropertyChanged("loaiCongTrinh");
					this.OnloaiCongTrinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DuAn_BangChamCong", Storage="_BangChamCongs", ThisKey="maDuAn", OtherKey="maDuAn")]
		public EntitySet<BangChamCong> BangChamCongs
		{
			get
			{
				return this._BangChamCongs;
			}
			set
			{
				this._BangChamCongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DuAn_CongViecDuAn", Storage="_CongViecDuAns", ThisKey="maDuAn", OtherKey="maDuAn")]
		public EntitySet<CongViecDuAn> CongViecDuAns
		{
			get
			{
				return this._CongViecDuAns;
			}
			set
			{
				this._CongViecDuAns.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DuAn_CongViecDuAn1", Storage="_CongViecDuAns1", ThisKey="maDuAn", OtherKey="maDuAn")]
		public EntitySet<CongViecDuAn> CongViecDuAns1
		{
			get
			{
				return this._CongViecDuAns1;
			}
			set
			{
				this._CongViecDuAns1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DuAn_ThaoLuanDuAn", Storage="_ThaoLuanDuAns", ThisKey="maDuAn", OtherKey="maDuAn")]
		public EntitySet<ThaoLuanDuAn> ThaoLuanDuAns
		{
			get
			{
				return this._ThaoLuanDuAns;
			}
			set
			{
				this._ThaoLuanDuAns.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DuAn_ThaoLuanDuAn1", Storage="_ThaoLuanDuAns1", ThisKey="maDuAn", OtherKey="maDuAn")]
		public EntitySet<ThaoLuanDuAn> ThaoLuanDuAns1
		{
			get
			{
				return this._ThaoLuanDuAns1;
			}
			set
			{
				this._ThaoLuanDuAns1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiaChi_DuAn", Storage="_DiaChi", ThisKey="maDiaChi", OtherKey="maDiaChi", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public DiaChi DiaChi
		{
			get
			{
				return this._DiaChi.Entity;
			}
			set
			{
				DiaChi previousValue = this._DiaChi.Entity;
				if (((previousValue != value) 
							|| (this._DiaChi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DiaChi.Entity = null;
						previousValue.DuAns.Remove(this);
					}
					this._DiaChi.Entity = value;
					if ((value != null))
					{
						value.DuAns.Add(this);
						this._maDiaChi = value.maDiaChi;
					}
					else
					{
						this._maDiaChi = default(string);
					}
					this.SendPropertyChanged("DiaChi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiaChi_DuAn1", Storage="_DiaChi1", ThisKey="maDiaChi", OtherKey="maDiaChi", IsForeignKey=true)]
		public DiaChi DiaChi1
		{
			get
			{
				return this._DiaChi1.Entity;
			}
			set
			{
				DiaChi previousValue = this._DiaChi1.Entity;
				if (((previousValue != value) 
							|| (this._DiaChi1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DiaChi1.Entity = null;
						previousValue.DuAns1.Remove(this);
					}
					this._DiaChi1.Entity = value;
					if ((value != null))
					{
						value.DuAns1.Add(this);
						this._maDiaChi = value.maDiaChi;
					}
					else
					{
						this._maDiaChi = default(string);
					}
					this.SendPropertyChanged("DiaChi1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BangChamCongs(BangChamCong entity)
		{
			this.SendPropertyChanging();
			entity.DuAn = this;
		}
		
		private void detach_BangChamCongs(BangChamCong entity)
		{
			this.SendPropertyChanging();
			entity.DuAn = null;
		}
		
		private void attach_CongViecDuAns(CongViecDuAn entity)
		{
			this.SendPropertyChanging();
			entity.DuAn = this;
		}
		
		private void detach_CongViecDuAns(CongViecDuAn entity)
		{
			this.SendPropertyChanging();
			entity.DuAn = null;
		}
		
		private void attach_CongViecDuAns1(CongViecDuAn entity)
		{
			this.SendPropertyChanging();
			entity.DuAn1 = this;
		}
		
		private void detach_CongViecDuAns1(CongViecDuAn entity)
		{
			this.SendPropertyChanging();
			entity.DuAn1 = null;
		}
		
		private void attach_ThaoLuanDuAns(ThaoLuanDuAn entity)
		{
			this.SendPropertyChanging();
			entity.DuAn = this;
		}
		
		private void detach_ThaoLuanDuAns(ThaoLuanDuAn entity)
		{
			this.SendPropertyChanging();
			entity.DuAn = null;
		}
		
		private void attach_ThaoLuanDuAns1(ThaoLuanDuAn entity)
		{
			this.SendPropertyChanging();
			entity.DuAn1 = this;
		}
		
		private void detach_ThaoLuanDuAns1(ThaoLuanDuAn entity)
		{
			this.SendPropertyChanging();
			entity.DuAn1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maNhanVien;
		
		private string _tenNhanVien;
		
		private string _maDiaChi;
		
		private string _soDienThoai;
		
		private string _gioiTinh;
		
		private System.DateTime _ngaySinh;
		
		private string _maPhongBan;
		
		private string _maChucVu;
		
		private string _taiKhoan;
		
		private EntitySet<BangChamCong> _BangChamCongs;
		
		private EntitySet<BangLuong> _BangLuongs;
		
		private EntityRef<ChucVu> _ChucVu;
		
		private EntityRef<DiaChi> _DiaChi;
		
		private EntityRef<PhongBan> _PhongBan;
		
		private EntityRef<TaiKhoan> _TaiKhoan1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNhanVienChanging(string value);
    partial void OnmaNhanVienChanged();
    partial void OntenNhanVienChanging(string value);
    partial void OntenNhanVienChanged();
    partial void OnmaDiaChiChanging(string value);
    partial void OnmaDiaChiChanged();
    partial void OnsoDienThoaiChanging(string value);
    partial void OnsoDienThoaiChanged();
    partial void OngioiTinhChanging(string value);
    partial void OngioiTinhChanged();
    partial void OnngaySinhChanging(System.DateTime value);
    partial void OnngaySinhChanged();
    partial void OnmaPhongBanChanging(string value);
    partial void OnmaPhongBanChanged();
    partial void OnmaChucVuChanging(string value);
    partial void OnmaChucVuChanged();
    partial void OntaiKhoanChanging(string value);
    partial void OntaiKhoanChanged();
    #endregion
		
		public NhanVien()
		{
			this._BangChamCongs = new EntitySet<BangChamCong>(new Action<BangChamCong>(this.attach_BangChamCongs), new Action<BangChamCong>(this.detach_BangChamCongs));
			this._BangLuongs = new EntitySet<BangLuong>(new Action<BangLuong>(this.attach_BangLuongs), new Action<BangLuong>(this.detach_BangLuongs));
			this._ChucVu = default(EntityRef<ChucVu>);
			this._DiaChi = default(EntityRef<DiaChi>);
			this._PhongBan = default(EntityRef<PhongBan>);
			this._TaiKhoan1 = default(EntityRef<TaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVien", DbType="NChar(14) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maNhanVien
		{
			get
			{
				return this._maNhanVien;
			}
			set
			{
				if ((this._maNhanVien != value))
				{
					this.OnmaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._maNhanVien = value;
					this.SendPropertyChanged("maNhanVien");
					this.OnmaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNhanVien", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenNhanVien
		{
			get
			{
				return this._tenNhanVien;
			}
			set
			{
				if ((this._tenNhanVien != value))
				{
					this.OntenNhanVienChanging(value);
					this.SendPropertyChanging();
					this._tenNhanVien = value;
					this.SendPropertyChanged("tenNhanVien");
					this.OntenNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maDiaChi", DbType="NChar(14) NOT NULL", CanBeNull=false)]
		public string maDiaChi
		{
			get
			{
				return this._maDiaChi;
			}
			set
			{
				if ((this._maDiaChi != value))
				{
					if (this._DiaChi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaDiaChiChanging(value);
					this.SendPropertyChanging();
					this._maDiaChi = value;
					this.SendPropertyChanged("maDiaChi");
					this.OnmaDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soDienThoai", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string soDienThoai
		{
			get
			{
				return this._soDienThoai;
			}
			set
			{
				if ((this._soDienThoai != value))
				{
					this.OnsoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._soDienThoai = value;
					this.SendPropertyChanged("soDienThoai");
					this.OnsoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinh", DbType="NVarChar(3) NOT NULL", CanBeNull=false)]
		public string gioiTinh
		{
			get
			{
				return this._gioiTinh;
			}
			set
			{
				if ((this._gioiTinh != value))
				{
					this.OngioiTinhChanging(value);
					this.SendPropertyChanging();
					this._gioiTinh = value;
					this.SendPropertyChanged("gioiTinh");
					this.OngioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaySinh", DbType="Date NOT NULL")]
		public System.DateTime ngaySinh
		{
			get
			{
				return this._ngaySinh;
			}
			set
			{
				if ((this._ngaySinh != value))
				{
					this.OnngaySinhChanging(value);
					this.SendPropertyChanging();
					this._ngaySinh = value;
					this.SendPropertyChanged("ngaySinh");
					this.OnngaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPhongBan", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string maPhongBan
		{
			get
			{
				return this._maPhongBan;
			}
			set
			{
				if ((this._maPhongBan != value))
				{
					if (this._PhongBan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaPhongBanChanging(value);
					this.SendPropertyChanging();
					this._maPhongBan = value;
					this.SendPropertyChanged("maPhongBan");
					this.OnmaPhongBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maChucVu", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string maChucVu
		{
			get
			{
				return this._maChucVu;
			}
			set
			{
				if ((this._maChucVu != value))
				{
					if (this._ChucVu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaChucVuChanging(value);
					this.SendPropertyChanging();
					this._maChucVu = value;
					this.SendPropertyChanged("maChucVu");
					this.OnmaChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taiKhoan", DbType="NChar(15)")]
		public string taiKhoan
		{
			get
			{
				return this._taiKhoan;
			}
			set
			{
				if ((this._taiKhoan != value))
				{
					if (this._TaiKhoan1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OntaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._taiKhoan = value;
					this.SendPropertyChanged("taiKhoan");
					this.OntaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_BangChamCong", Storage="_BangChamCongs", ThisKey="maNhanVien", OtherKey="maNhanVien")]
		public EntitySet<BangChamCong> BangChamCongs
		{
			get
			{
				return this._BangChamCongs;
			}
			set
			{
				this._BangChamCongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_BangLuong", Storage="_BangLuongs", ThisKey="maNhanVien", OtherKey="maNhanVien")]
		public EntitySet<BangLuong> BangLuongs
		{
			get
			{
				return this._BangLuongs;
			}
			set
			{
				this._BangLuongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChucVu_NhanVien", Storage="_ChucVu", ThisKey="maChucVu", OtherKey="maChucVu", IsForeignKey=true)]
		public ChucVu ChucVu
		{
			get
			{
				return this._ChucVu.Entity;
			}
			set
			{
				ChucVu previousValue = this._ChucVu.Entity;
				if (((previousValue != value) 
							|| (this._ChucVu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChucVu.Entity = null;
						previousValue.NhanViens.Remove(this);
					}
					this._ChucVu.Entity = value;
					if ((value != null))
					{
						value.NhanViens.Add(this);
						this._maChucVu = value.maChucVu;
					}
					else
					{
						this._maChucVu = default(string);
					}
					this.SendPropertyChanged("ChucVu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiaChi_NhanVien", Storage="_DiaChi", ThisKey="maDiaChi", OtherKey="maDiaChi", IsForeignKey=true)]
		public DiaChi DiaChi
		{
			get
			{
				return this._DiaChi.Entity;
			}
			set
			{
				DiaChi previousValue = this._DiaChi.Entity;
				if (((previousValue != value) 
							|| (this._DiaChi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DiaChi.Entity = null;
						previousValue.NhanViens.Remove(this);
					}
					this._DiaChi.Entity = value;
					if ((value != null))
					{
						value.NhanViens.Add(this);
						this._maDiaChi = value.maDiaChi;
					}
					else
					{
						this._maDiaChi = default(string);
					}
					this.SendPropertyChanged("DiaChi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongBan_NhanVien", Storage="_PhongBan", ThisKey="maPhongBan", OtherKey="maPhongBan", IsForeignKey=true)]
		public PhongBan PhongBan
		{
			get
			{
				return this._PhongBan.Entity;
			}
			set
			{
				PhongBan previousValue = this._PhongBan.Entity;
				if (((previousValue != value) 
							|| (this._PhongBan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhongBan.Entity = null;
						previousValue.NhanViens.Remove(this);
					}
					this._PhongBan.Entity = value;
					if ((value != null))
					{
						value.NhanViens.Add(this);
						this._maPhongBan = value.maPhongBan;
					}
					else
					{
						this._maPhongBan = default(string);
					}
					this.SendPropertyChanged("PhongBan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_NhanVien", Storage="_TaiKhoan1", ThisKey="taiKhoan", OtherKey="taiKhoan1", IsForeignKey=true)]
		public TaiKhoan TaiKhoan1
		{
			get
			{
				return this._TaiKhoan1.Entity;
			}
			set
			{
				TaiKhoan previousValue = this._TaiKhoan1.Entity;
				if (((previousValue != value) 
							|| (this._TaiKhoan1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TaiKhoan1.Entity = null;
						previousValue.NhanViens.Remove(this);
					}
					this._TaiKhoan1.Entity = value;
					if ((value != null))
					{
						value.NhanViens.Add(this);
						this._taiKhoan = value.taiKhoan1;
					}
					else
					{
						this._taiKhoan = default(string);
					}
					this.SendPropertyChanged("TaiKhoan1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BangChamCongs(BangChamCong entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_BangChamCongs(BangChamCong entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
		
		private void attach_BangLuongs(BangLuong entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_BangLuongs(BangLuong entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhongBan")]
	public partial class PhongBan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maPhongBan;
		
		private string _tenPhongBan;
		
		private EntitySet<NhanVien> _NhanViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaPhongBanChanging(string value);
    partial void OnmaPhongBanChanged();
    partial void OntenPhongBanChanging(string value);
    partial void OntenPhongBanChanged();
    #endregion
		
		public PhongBan()
		{
			this._NhanViens = new EntitySet<NhanVien>(new Action<NhanVien>(this.attach_NhanViens), new Action<NhanVien>(this.detach_NhanViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPhongBan", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maPhongBan
		{
			get
			{
				return this._maPhongBan;
			}
			set
			{
				if ((this._maPhongBan != value))
				{
					this.OnmaPhongBanChanging(value);
					this.SendPropertyChanging();
					this._maPhongBan = value;
					this.SendPropertyChanged("maPhongBan");
					this.OnmaPhongBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenPhongBan", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string tenPhongBan
		{
			get
			{
				return this._tenPhongBan;
			}
			set
			{
				if ((this._tenPhongBan != value))
				{
					this.OntenPhongBanChanging(value);
					this.SendPropertyChanging();
					this._tenPhongBan = value;
					this.SendPropertyChanged("tenPhongBan");
					this.OntenPhongBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongBan_NhanVien", Storage="_NhanViens", ThisKey="maPhongBan", OtherKey="maPhongBan")]
		public EntitySet<NhanVien> NhanViens
		{
			get
			{
				return this._NhanViens;
			}
			set
			{
				this._NhanViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.PhongBan = this;
		}
		
		private void detach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.PhongBan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _taiKhoan1;
		
		private string _matKhau;
		
		private int _nhoMatKhau;
		
		private string _maNhanVien;
		
		private EntitySet<NhanVien> _NhanViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntaiKhoan1Changing(string value);
    partial void OntaiKhoan1Changed();
    partial void OnmatKhauChanging(string value);
    partial void OnmatKhauChanged();
    partial void OnnhoMatKhauChanging(int value);
    partial void OnnhoMatKhauChanged();
    partial void OnmaNhanVienChanging(string value);
    partial void OnmaNhanVienChanged();
    #endregion
		
		public TaiKhoan()
		{
			this._NhanViens = new EntitySet<NhanVien>(new Action<NhanVien>(this.attach_NhanViens), new Action<NhanVien>(this.detach_NhanViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="taiKhoan", Storage="_taiKhoan1", DbType="NChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string taiKhoan1
		{
			get
			{
				return this._taiKhoan1;
			}
			set
			{
				if ((this._taiKhoan1 != value))
				{
					this.OntaiKhoan1Changing(value);
					this.SendPropertyChanging();
					this._taiKhoan1 = value;
					this.SendPropertyChanged("taiKhoan1");
					this.OntaiKhoan1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matKhau", DbType="NChar(15) NOT NULL", CanBeNull=false)]
		public string matKhau
		{
			get
			{
				return this._matKhau;
			}
			set
			{
				if ((this._matKhau != value))
				{
					this.OnmatKhauChanging(value);
					this.SendPropertyChanging();
					this._matKhau = value;
					this.SendPropertyChanged("matKhau");
					this.OnmatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhoMatKhau", DbType="Int NOT NULL")]
		public int nhoMatKhau
		{
			get
			{
				return this._nhoMatKhau;
			}
			set
			{
				if ((this._nhoMatKhau != value))
				{
					this.OnnhoMatKhauChanging(value);
					this.SendPropertyChanging();
					this._nhoMatKhau = value;
					this.SendPropertyChanged("nhoMatKhau");
					this.OnnhoMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVien", DbType="NChar(14)")]
		public string maNhanVien
		{
			get
			{
				return this._maNhanVien;
			}
			set
			{
				if ((this._maNhanVien != value))
				{
					this.OnmaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._maNhanVien = value;
					this.SendPropertyChanged("maNhanVien");
					this.OnmaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_NhanVien", Storage="_NhanViens", ThisKey="taiKhoan1", OtherKey="taiKhoan")]
		public EntitySet<NhanVien> NhanViens
		{
			get
			{
				return this._NhanViens;
			}
			set
			{
				this._NhanViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan1 = this;
		}
		
		private void detach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThaoLuanDuAn")]
	public partial class ThaoLuanDuAn : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maThaoLuan;
		
		private string _chuDeThaoLuan;
		
		private System.Nullable<System.DateTime> _ngayThaoLuan;
		
		private string _noiDungThaoLuan;
		
		private string _maDuAn;
		
		private EntityRef<DuAn> _DuAn;
		
		private EntityRef<DuAn> _DuAn1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaThaoLuanChanging(int value);
    partial void OnmaThaoLuanChanged();
    partial void OnchuDeThaoLuanChanging(string value);
    partial void OnchuDeThaoLuanChanged();
    partial void OnngayThaoLuanChanging(System.Nullable<System.DateTime> value);
    partial void OnngayThaoLuanChanged();
    partial void OnnoiDungThaoLuanChanging(string value);
    partial void OnnoiDungThaoLuanChanged();
    partial void OnmaDuAnChanging(string value);
    partial void OnmaDuAnChanged();
    #endregion
		
		public ThaoLuanDuAn()
		{
			this._DuAn = default(EntityRef<DuAn>);
			this._DuAn1 = default(EntityRef<DuAn>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maThaoLuan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maThaoLuan
		{
			get
			{
				return this._maThaoLuan;
			}
			set
			{
				if ((this._maThaoLuan != value))
				{
					this.OnmaThaoLuanChanging(value);
					this.SendPropertyChanging();
					this._maThaoLuan = value;
					this.SendPropertyChanged("maThaoLuan");
					this.OnmaThaoLuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chuDeThaoLuan", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string chuDeThaoLuan
		{
			get
			{
				return this._chuDeThaoLuan;
			}
			set
			{
				if ((this._chuDeThaoLuan != value))
				{
					this.OnchuDeThaoLuanChanging(value);
					this.SendPropertyChanging();
					this._chuDeThaoLuan = value;
					this.SendPropertyChanged("chuDeThaoLuan");
					this.OnchuDeThaoLuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayThaoLuan", DbType="Date")]
		public System.Nullable<System.DateTime> ngayThaoLuan
		{
			get
			{
				return this._ngayThaoLuan;
			}
			set
			{
				if ((this._ngayThaoLuan != value))
				{
					this.OnngayThaoLuanChanging(value);
					this.SendPropertyChanging();
					this._ngayThaoLuan = value;
					this.SendPropertyChanged("ngayThaoLuan");
					this.OnngayThaoLuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noiDungThaoLuan", DbType="NVarChar(350)")]
		public string noiDungThaoLuan
		{
			get
			{
				return this._noiDungThaoLuan;
			}
			set
			{
				if ((this._noiDungThaoLuan != value))
				{
					this.OnnoiDungThaoLuanChanging(value);
					this.SendPropertyChanging();
					this._noiDungThaoLuan = value;
					this.SendPropertyChanged("noiDungThaoLuan");
					this.OnnoiDungThaoLuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maDuAn", DbType="NChar(14)")]
		public string maDuAn
		{
			get
			{
				return this._maDuAn;
			}
			set
			{
				if ((this._maDuAn != value))
				{
					if ((this._DuAn.HasLoadedOrAssignedValue || this._DuAn1.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaDuAnChanging(value);
					this.SendPropertyChanging();
					this._maDuAn = value;
					this.SendPropertyChanged("maDuAn");
					this.OnmaDuAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DuAn_ThaoLuanDuAn", Storage="_DuAn", ThisKey="maDuAn", OtherKey="maDuAn", IsForeignKey=true, DeleteRule="CASCADE")]
		public DuAn DuAn
		{
			get
			{
				return this._DuAn.Entity;
			}
			set
			{
				DuAn previousValue = this._DuAn.Entity;
				if (((previousValue != value) 
							|| (this._DuAn.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DuAn.Entity = null;
						previousValue.ThaoLuanDuAns.Remove(this);
					}
					this._DuAn.Entity = value;
					if ((value != null))
					{
						value.ThaoLuanDuAns.Add(this);
						this._maDuAn = value.maDuAn;
					}
					else
					{
						this._maDuAn = default(string);
					}
					this.SendPropertyChanged("DuAn");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DuAn_ThaoLuanDuAn1", Storage="_DuAn1", ThisKey="maDuAn", OtherKey="maDuAn", IsForeignKey=true)]
		public DuAn DuAn1
		{
			get
			{
				return this._DuAn1.Entity;
			}
			set
			{
				DuAn previousValue = this._DuAn1.Entity;
				if (((previousValue != value) 
							|| (this._DuAn1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DuAn1.Entity = null;
						previousValue.ThaoLuanDuAns1.Remove(this);
					}
					this._DuAn1.Entity = value;
					if ((value != null))
					{
						value.ThaoLuanDuAns1.Add(this);
						this._maDuAn = value.maDuAn;
					}
					else
					{
						this._maDuAn = default(string);
					}
					this.SendPropertyChanged("DuAn1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
