//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=|DataDirectory|\\QLLD.mdf;Integrated " +
            "Security=True;Connect Timeout=30")]
        public string QLLDConnectionString {
            get {
                return ((string)(this["QLLDConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=D:\\PTUD\\Nhom01_DeTai04_PTUD_13A_2019" +
            "\\DB\\QLLD.mdf;Integrated Security=True;Connect Timeout=30")]
        public string QLLDConnectionString1 {
            get {
                return ((string)(this["QLLDConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-PGNO1ME\\SQLEXPRESS;Initial Catalog=QuanLyLaoDong;Integrated S" +
            "ecurity=True")]
        public string QuanLyLaoDongConnectionString {
            get {
                return ((string)(this["QuanLyLaoDongConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-PGNO1ME\\SQLEXPRESS;Initial Catalog=D:\\PTUD\\NHOM01_DETAI04_PTU" +
            "D_13A_2019\\DB\\QLLD.MDF;Integrated Security=True")]
        public string D__PTUD_NHOM01_DETAI04_PTUD_13A_2019_DB_QLLD_MDFConnectionString {
            get {
                return ((string)(this["D__PTUD_NHOM01_DETAI04_PTUD_13A_2019_DB_QLLD_MDFConnectionString"]));
            }
        }
    }
}
